### ISSUE TITLE
Timestamp is missing

### ISSUE THREAD

**Issue by LaurianeMarxer** [gaia-x-dases/common-profile#19]
Hello @quitterie-lcs,

In the statement example accessed a page the timestamp is missing.
https://github.com/gaia-x-dases/xapi-lms/blob/master/statements/accessed_page.md

**Comment by quitterie-lcs** [comment]
Hello @LaurianeMarxer, thanks for noticing it ! 
I'll open a PR to fix it. You'll be reviewer
